Added login page test
VolhaDzenisiuk/TestLoginPage pull request #1
Opened 2019-07-12 11:07 UTC by VolhaDzenisiuk

2019-07-14 10:59 UTC, EugenBorisik reviewed
Could also add class with By variables for point 2 from task 30. I believe that you know them and it will take 5 minutes

2019-07-14 14:02 UTC, VolhaDzenisiuk commented
@EugenBorisik please check src/test/java/LoginPage.java file, it contains By variables. Thank you

2019-07-14 14:18 UTC, EugenBorisik commented
All of them were found using By.xpath(..) method. I also want to see other methods like By.id, By.cssSelector, etc.

2019-07-22 14:39 UTC, EugenBorisik approved these changes
Also remember about By.linkText, By.partialLinkText, By.tagName

2019-08-12 10:33 UTC, VolhaDzenisiuk commented
@EugenBorisik please review task 40.

2019-08-18 07:11 UTC, EugenBorisik requested changes

2019-08-18 07:11 UTC, EugenBorisik commented on src/test/java/pages/AlertPage.java
> +    public static By JS_ALERT = By.xpath("//div[@class=\"example\"]/ul/li[1]/button");
Use onClick attribute for these 3 locators

2019-08-18 07:11 UTC, EugenBorisik commented on src/test/java/tests/AlertTest.java
> +            alert.sendKeys("alert test");
Move your text in variable and use it here and in assertion

2019-08-18 07:11 UTC, EugenBorisik commented on src/test/java/tests/FrameTest.java
> +        ((JavascriptExecutor)driver).executeScript("tinyMCE.activeEditor.setContent('')");
You can set text without JavascriptExecutor. Just switch to the frame and send keys to body

2019-08-26 09:29 UTC, EugenBorisik approved these changes

2019-08-29 10:44 UTC, merged